//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Task1_BDO.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Timesheets
    {
        public int Sheet_Id { get; set; }
        public Nullable<int> Task_Id { get; set; }
        public string Employee_Id { get; set; }
    
        public virtual AspNetUsers AspNetUsers { get; set; }
        public virtual Tasks Tasks { get; set; }
    }
}
